#!/bin/bash
#
# usage: $0 [<id> ...]
#
# Note: requires PATH to contain concubine and solver executables.

# make sure we'r in the experiments directory
if ! pwd | grep -q "examples$"
then
  echo "error: please execute me in the experiments directory" >&2
  exit 1
fi

# set experiments
[ -z "$*" ] \
  && experiments=$(grep -o "^| \w\+\s\+|" README.md | awk '{print $2}') \
  || experiments=$*

# DEBUG: expect concubine in parent directory
[ ! -z "$TEST" ] && command concubine &> /dev/null || PATH="$(realpath ..):$PATH"

for i in $experiments
do
  # split experiment into bash array {id, dir, cmd}
  IFS='|' read -r -a exp <<< \
    $(grep "^| $i\s\+|" README.md | sed -e 's/^.\s\+//' -e 's/\s\+.$//')

  [ "${#exp[@]}" = 0 ] && echo "error: missing experiment $i" >&2 && exit 1

  # remove leading / trailing whitespaces
  shopt -s extglob
  exp=("${exp[@]/#+([[:blank:]])/}") # remove leading
  exp=("${exp[@]/%+([[:blank:]])/}") # remove trailing

  # run experiment
  echo "running experiment ${exp[0]}: ${exp[1]}/${exp[2]}"
  pushd ${exp[1]} > /dev/null
  ./${exp[2]} # || exit 1 # TODO: kill whole run?
  popd > /dev/null
done
